import type { BoardGame } from "./types";

export const boardGames: BoardGame[] = [
  {
    id: "game-ark-nova",
    slug: "ark-nova",
    title: "Ark Nova",
    titleKo: "아크 노바",
    yearPublished: 2021,
    playerCount: "1-4",
    playTime: "90-150분",
    complexity: "전략",
    publisher: "Capstone Games",
    designers: ["Mathias Wigge"],
    mechanics: ["카드 드래프팅", "타일 배치", "액션 큐"],
    tags: ["전략", "동물", "카드", "타일"],
    summary: "보전 프로젝트, 후원 카드, 액션 카드 타이밍을 조합해 현대적인 동물원을 만드는 전략 게임입니다.",
    rulebookStatus: "등록됨",
    coverGradient: "from-moss via-emerald-700 to-ink"
  },
  {
    id: "game-wingspan",
    slug: "wingspan",
    title: "Wingspan",
    titleKo: "윙스팬",
    yearPublished: 2019,
    playerCount: "1-5",
    playTime: "40-70분",
    complexity: "중급",
    publisher: "Stonemaier Games",
    designers: ["Elizabeth Hargrave"],
    mechanics: ["엔진 빌딩", "주사위 드래프팅", "세트 컬렉션"],
    tags: ["가족", "카드", "동물"],
    summary: "서식지에 새를 모으고 먹이, 알, 카드를 점수로 연결하는 아름다운 엔진 빌딩 게임입니다.",
    rulebookStatus: "등록됨",
    coverGradient: "from-coral via-rose-500 to-saffron"
  },
  {
    id: "game-brass-birmingham",
    slug: "brass-birmingham",
    title: "Brass: Birmingham",
    titleKo: "브라스: 버밍엄",
    yearPublished: 2018,
    playerCount: "2-4",
    playTime: "60-120분",
    complexity: "전략",
    publisher: "Roxley",
    designers: ["Gavan Brown", "Matt Tolman", "Martin Wallace"],
    mechanics: ["네트워크 건설", "핸드 관리", "경제 계획"],
    tags: ["전략", "경제", "네트워크", "카드"],
    summary: "운하와 철도 시대를 거치며 산업, 운송로, 시장 수요를 설계하는 깊이 있는 경제 전략 게임입니다.",
    rulebookStatus: "검토 중",
    coverGradient: "from-zinc-800 via-stone-700 to-saffron"
  },
  {
    id: "game-cascadia",
    slug: "cascadia",
    title: "Cascadia",
    titleKo: "캐스캐디아",
    yearPublished: 2021,
    playerCount: "1-4",
    playTime: "30-45분",
    complexity: "입문",
    publisher: "Flatout Games",
    designers: ["Randy Flynn"],
    mechanics: ["타일 배치", "패턴 만들기", "드래프팅"],
    tags: ["가족", "타일", "동물", "퍼즐"],
    summary: "서식지 타일과 야생동물 토큰을 골라 점수 패턴을 완성하는 편안한 퍼즐형 보드게임입니다.",
    rulebookStatus: "텍스트 필요",
    coverGradient: "from-sky-700 via-moss to-lime-600"
  },
  {
    id: "game-dominion",
    slug: "dominion",
    title: "Dominion",
    titleKo: "도미니언",
    yearPublished: 2008,
    playerCount: "2-4",
    playTime: "30분",
    complexity: "중급",
    publisher: "Rio Grande Games",
    designers: ["Donald X. Vaccarino"],
    mechanics: ["덱 빌딩", "카드 조합", "핸드 관리"],
    tags: ["카드", "덱빌딩", "전략"],
    summary: "덱 빌딩 장르를 대표하는 게임으로, 매 턴 카드를 구매해 나만의 왕국 덱을 성장시킵니다.",
    rulebookStatus: "검토 중",
    coverGradient: "from-amber-700 via-lime-700 to-ink"
  },
  {
    id: "game-ticket-to-ride",
    slug: "ticket-to-ride",
    title: "Ticket to Ride",
    titleKo: "티켓 투 라이드",
    yearPublished: 2004,
    playerCount: "2-5",
    playTime: "30-60분",
    complexity: "입문",
    publisher: "Days of Wonder",
    designers: ["Alan R. Moon"],
    mechanics: ["세트 컬렉션", "노선 연결", "핸드 관리"],
    tags: ["가족", "입문", "네트워크", "카드"],
    summary: "기차 카드를 모아 도시 사이의 노선을 연결하고 목적지 티켓을 완성하는 입문용 명작입니다.",
    rulebookStatus: "등록됨",
    coverGradient: "from-sky-800 via-cyan-700 to-coral"
  },
  {
    id: "game-tichu",
    slug: "tichu",
    title: "Tichu",
    titleKo: "티츄",
    yearPublished: 1991,
    playerCount: "4",
    playTime: "60분",
    complexity: "중급",
    publisher: "Fata Morgana",
    designers: ["Urs Hostettler"],
    mechanics: ["핸드 관리", "팀전", "클라이밍", "카운팅"],
    tags: ["카드", "팀전(협력)", "카운팅", "심리"],
    summary: "두 명씩 팀을 이뤄 손패를 털고, 선언과 카운팅, 심리전으로 큰 점수를 노리는 파트너십 카드 게임입니다.",
    rulebookStatus: "검토 중",
    coverGradient: "from-red-700 via-amber-600 to-ink"
  }
];

export function getBoardGameBySlug(slug: string) {
  return boardGames.find((game) => game.slug === slug);
}
